# Generated by Django 4.2.9 on 2024-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addtype', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'public.pi_address',
            },
        ),
    ]
