# Generated by Django 4.2.9 on 2024-01-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PiAddress',
        ),
    ]
